// Tüm component'leri tek yerden export etmek için
export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Projects } from './Projects'
export { default as Contact } from './Contact'
export { default as Services } from './Services'
export { default as Navigation } from './Navigation'